INSERT INTO CATEGORY(TITLE, DESCRIPTION) VALUES ('평창1', '평창이 주제인 활동들1');

INSERT INTO MISSION(TITLE, LOCATION, DESCRIPTION, DIFFICULTY) VALUES ('평창맛집', '강원도 평창시','평창 주변 맛집을 다녀오세요', '하');
INSERT INTO MISSION(TITLE, LOCATION, DESCRIPTION, DIFFICULTY) VALUES ('평창명소', '강원도 평창시','평창에 명소에서 이런 사진을 찍어오세요', '상');
INSERT INTO MISSION(TITLE, LOCATION, DESCRIPTION, DIFFICULTY) VALUES ('평창놀거리', '강원도 평창시','숙소에 돌아와서 이런 놀이를 즐기세요', '중');

INSERT INTO CATEGORY_MISSION(CATEGORY_ID, MISSION_ID) VALUES ('1', '1');
INSERT INTO CATEGORY_MISSION(CATEGORY_ID, MISSION_ID) VALUES ('1', '2');
INSERT INTO CATEGORY_MISSION(CATEGORY_ID, MISSION_ID) VALUES ('1', '3');

INSERT INTO KEYWORD(KEYWORD) VALUES ('라면');
INSERT INTO KEYWORD(KEYWORD) VALUES ('매운맛');
INSERT INTO KEYWORD(KEYWORD) VALUES ('고추장');
INSERT INTO KEYWORD(KEYWORD) VALUES ('동물');
INSERT INTO KEYWORD(KEYWORD) VALUES ('목장');

INSERT INTO NOLZA_USER(EMAIL, NATION, USER_NAME, PASSWORD) VALUES ('nolza@naver.com', '대한민국', '놀자', '1234');


